### ISSUE TITLE
Localization for English and Bahasa Indonesia

### ISSUE THREAD

**Issue by rmRizki** [baduthutan/GoodHusband#7]
**User Story:** 
As a user, I want the app to support English and Bahasa Indonesia so that it is accessible in my preferred language.

**Tasks:**
- [ ] Translate app content to Bahasa Indonesia.
- [ ] Implement localization support in the app.
- [ ] Add language selection option.

**Comment by rmRizki** [comment]
Reference for now:

https://medium.com/@hyleedevelop/ios-localization-tutorial-in-swiftui-using-string-catalog-9307953d8082
